# -- Site Configuration --

baseURL = "//www.ray34g.com/"

defaultContentLanguage = "ja"

canonifyURLs = false

enableRobotsTXT = true
summaryLength = 0

buildDrafts = false
buildFuture = false

enableGitInfo = true

[pagination]
pagerSize = 12

[permalinks]
posts = "/:section/:year/:month/:slug/"

[frontmatter]
date = ["date", "publishDate", ":git", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate", ":fileModTime"]

[taxonomies]

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[outputs]
page = ["HTML", "AMP"]
home = ["HTML", "AMP", "RSS"]