# -- Site Configuration --

# theme = ["tetra"]
# themesDir = "../../"

baseURL = "//www.ray34g.com/"

defaultContentLanguage = "ja"
# disableLanguages = ["en"]

# canonifyURLs = true

enableRobotsTXT = true
summaryLength = 0

buildDrafts = false
buildFuture = false

# googleAnalytics = "G-XXXXXXXXX"
# enableGitInfo = true

[pagination]
pagerSize = 12

[permalinks]
posts = "/:section/:year/:month/:slug/"

[frontmatter]
date = ["date", "publishDate", ":git", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate", ":fileModTime"]

[taxonomies]
# author = "authors"
# category = "categories"
# series = "series"
# tag = "tags"

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[outputs]
page = ["HTML", "AMP"]
home = ["HTML", "AMP", "RSS"]
# home = [ "HTML", "AMP", "RSS", "WebAppManifest" ]
# section = [ "HTML", "AMP", "RSS" ]
# taxonomy = [ "HTML", "AMP" ]
# term = [ "HTML", "AMP", "RSS" ]

# [outputFormats]
# [outputFormats.WebAppManifest]
#   baseName = "site"
#   mediaType = "application/json"
