name: Deploy static site to GitHub Pages

on:
  workflow_run:
    workflows: ["Build static site"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      build_run_id:
        description: 'Build workflow run ID to fetch artifacts from'
        required: true

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ray34g-cluster-g-arc-runner-set
    container:
      image: ghcr.io/ray34g/arc-runner-node-hugo:0.139.3
    steps:
      - name: Set run ID
        id: set-run-id
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "RUN_ID=${{ github.event.inputs.build_run_id }}" >> $GITHUB_ENV
          else
            echo "RUN_ID=${{ github.event.workflow_run.id }}" >> $GITHUB_ENV
          fi

      - name: Debug list artifacts via API
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ env.RUN_ID }}
        run: |
          curl -s -H "Authorization: Bearer $GH_PAT" \
                -H "Accept: application/vnd.github+json" \
                "https://api.github.com/repos/ray34g/ray34g.github.io/actions/runs/${RUN_ID}/artifacts" \
                | jq '.'
      - name: Download github-pages artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          run-id: ${{ env.RUN_ID }}
          repository: ray34g/ray34g.github.io
          path: ./public
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-multiple: false
          if-no-files-found: error